export enum SourceType {
  MOVIE = 'MOVIE',
  TV_SHOW = 'TV_SHOW',
  BOOK = 'BOOK',
  VIDEO_GAME = 'VIDEO_GAME',
  KOREAN_DRAMA = 'KOREAN_DRAMA',
  JAPANESE_MANGA = 'JAPANESE_MANGA',
  JAPANESE_ANIME = 'JAPANESE_ANIME',
}
